### PR TITLE
Add "Support" For Composer 2

### PR DESCRIPTION
**Pull request by sprankhub**
See #4.

### CODE REVIEW

**Comment by sprankhub** [comment]
Please mind that `\Fooman\ComposerMagentoOptimizations\TruncatedComposerRepository` is still incompatible with Composer 2. However, since we do nothing if Composer 2 is detected, this is not a real issue.

**Comment by sprankhub** [comment]
Please also mind that this is untested :see_no_evil:

**Review by Seldaek — APPROVED** [review]
Seems reasonable to me. Note that Composer 2.1 should improve memory usage and so on even further so I really hope to see such hacky plugins that mess with Composer internals disappear in the long term.

**Comment by fooman** [comment]
Thanks @Seldaek for the ping and @sprankhub for tackling this. 

Indeed I believe with Composer 2.0 this plugin can just be removed from any installs with 2.1 even more so.

**Comment by fooman** [comment]
Thanks Simon - I think I'll make the notice even more explicit.

**Pull request merged**
